import operator
from typing import Annotated, List, TypedDict

# This is the "Medical Clipboard" passed between agents
class MedicalState(TypedDict):
    # The initial symptom report from the user
    symptoms: str
    
    # The diagnosis generated by the Medical Agent
    diagnosis: str
    
    # The treatment plan generated by the Pharmacy Agent
    treatment_plan: str
    
    # The critique from the Reviewer Agent
    critique: str
    
    # A list of all messages exchanged (Chat History)
    # operator.add tells LangGraph to APPEND new messages, not overwrite old ones
    messages: Annotated[List[str], operator.add]
    
    # Final approval status
    approved: bool

    revision_number: int